version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: idiotoflinux
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t idiotoflinux/k9c:$TAG ./build
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push idiotoflinux/k9c:$TAG